/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace ffi {

struct StructA;
struct StructB;

template<typename T>
struct VecWrapper
{
    const T *data;
    size_t len;
    size_t capacity;
};

struct StructB
{
    const StructA *_structA;
};

struct StructA
{
    const StructB *_structB;
};

extern "C" {

void test_hello();

void print_strings(const VecWrapper<const char*> *strings);

void _dummy(const StructA *a, const StructB *b);

} // extern "C"

} // namespace ffi
